baseurl = "http://example.netlify.io/"
relativeurls = false
languageCode = "en-us"
title = "Ahmad Qabazard"
theme = "hugo-prof"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
uglyURLS = false
enableEmoji = true
blogdir = "blog"

[permalinks]
    post = "blog/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]           # comment out this row, plus the name, url, and weight to omit  
   name = "Research"    
   url = "/research/"
   weight = 2
[[menu.main]]           # comment out this row, plus the name, url, and weight to omit 
   name = "Teaching"
   url = "/teaching/"
   weight = 3
[[menu.main]]           # comment out this row, plus the name, url, and weight to omit 
    name = "Blog"
    url = "/blog/"
    weight = 4
[[menu.main]]
    name = "CV"
    url = "/cv.pdf"
    weight = 5

[params]
    description = "Ahmad is a graduate student in political science" 
    subtitle = "I am interested in comparative politics"
    home_text = "I am interested in comparative politics."

    author = "Ahmad Qabazard"
    dateFormat = "2006/01/02"
    email = "ahmad-qabazard@uiowa.edu"
    github_username = "aq92"
    twitter_username = "AhmadQ992"  # leave empty quotes to omit
    gscholar_code = ""        # leave empty quotes to omit    

    page_color = "white"
    text_color = "black"
    link_color = "rgb(0, 0, 152)"
    hover_color = "rgb(255, 102, 0)"


    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
